---
title: "Python Workshop Final Project"
author: "George Davis"
format: dashboard
---




```{python}
import pandas as pd
import plotly.express as px
from itables import show 

# Load raw data from specified paths: child mortality

child_mort_raw = pd.read_csv("data/child_mortality_0_5_year_olds_dying_per_1000_born.csv")

# Applying 'drop' to remove the *geo* column and keeping the dataframe.
# child_mort_raw = child_mort_raw.drop(columns=["geo"])#

# Load raw data from specified paths: under five population

under_five_pop_raw = pd.read_csv("data/u5pop.csv")

# Applying 'drop' to remove the *geo* column and keeping the dataframe.
# under_five_pop_raw = under_five_pop_raw.drop(columns=["geo"])

#Keeping the renaming changes in the dataframe

child_mort_raw = child_mort_raw.rename(columns={"name": "country"})

# Keeping the renaming changes in the dataframe.
under_five_pop_raw = under_five_pop_raw.rename(columns={"name": "country"})

# Melt from wide to long format and adding a new dataframe 'child_mort_long'

child_mort_long = child_mort_raw.melt(
    id_vars=["geo", "country"],
    var_name="year",
    value_name="deaths"
).sort_values(by=["country", "year"])

# Melt from wide to long format and adding a new dataframe 'under_five_pop_long'

under_five_pop_long = under_five_pop_raw.melt(
    id_vars=["geo", "country"],
    var_name="year",
    value_name="population"
).sort_values(by=["country", "year"])

# Joining the two datasets using 'merge' into a new dataframe 'child_mort_pop_combined'

# Adding a new dataframe 'child_mort_pop_combined'

child_mort_pop_combined = pd.merge(child_mort_long, under_five_pop_long, on=["country", "year"], how="outer")

# Convert year to numeric using pd.to_numeric

child_mort_pop_combined["year"] = pd.to_numeric(child_mort_pop_combined["year"], errors="coerce")

# Creating a new dataframe with the range in years 2010 - 2020.

# Querying for the years
child_mort_pop_combined_2010_2020 = child_mort_pop_combined[child_mort_pop_combined["year"].between(2010, 2020)]

# Querying my selected a few countries in a new dataframe also displaying the range in years from 2010 to 2020.

child_mort_pop_combined_subset = child_mort_pop_combined_2010_2020.query("country.isin(['Ghana', 'Nigeria', 'Liberia', 'Senegal','Sierra Leone'])")

# Creating a line chart. 

fig_chart = px.line(
    child_mort_pop_combined_subset,
    x="year",
    y="deaths",
    markers=True,
    color="country"
)
fig_chart.update_layout(showlegend=False)

# Table section

# Subset the data to include `country`, `2010`, and `2020` columns only.
table_df = child_mort_raw[["country", "2010", "2020"]]

# Calculate difference of mortality rate between 2010 and 2020

table_df["Absolute Change"] = table_df["2010"] - table_df["2020"]

# Calculate relative change as the absolute change in mortality divided by 2010 rates.

table_df["Relative Change"] = table_df["2010"] / table_df["2020"] * 100

# Round to 0 decimal places and adding a % sign to the the relative change.

table_df["Relative Change"] = table_df["Relative Change"].round(0).astype(str) + "%"


child_mort_pop_combined_2010_2020 = child_mort_pop_combined_2010_2020.query("year == 2010")

# Compute highest child mortality rates
highest_row = child_mort_pop_combined_2010_2020.sort_values("deaths", ascending=False).head(1).squeeze()
highest_child_mortality_country = highest_row["country"]
highest_child_mortality_value = round(highest_row["deaths"], 1)

# Compute lowest child mortality rates
lowest_row = child_mort_pop_combined_2010_2020.sort_values("deaths", ascending=True).head(1).squeeze()
lowest_child_mortality_country = lowest_row["country"]
lowest_child_mortality_value = round(lowest_row["deaths"], 1)

# Compute average (population-weighted) child mortality
weighted_mean = (child_mort_pop_combined_2010_2020["deaths"] * child_mort_pop_combined_2010_2020["population"]).sum() / child_mort_pop_combined_2010_2020["population"].sum()
average_child_mortality_value = round(weighted_mean, 1)


# Largest 10 countries with child mortality rates (bar chart) with a blue color scale
top_10 = child_mort_pop_combined_2010_2020.nlargest(10, "population").sort_values("deaths", ascending=True)
bar_fig = px.bar(
    top_10,
    x="deaths",
    y="country",
    title="Child Mortality Rates in 10 Largest Countries",
    color="deaths",
    color_continuous_scale="Blues",
).update_layout(coloraxis_showscale=False)


# Create the map using plotly express. Convert the existing ISO3 codes to uppercase

child_mort_pop_combined_subset["geo_x"] = child_mort_pop_combined_subset["geo_y"].str.upper()

map_fig = px.choropleth(
    child_mort_pop_combined_subset,
    locations="geo_x",
    color="country",
    hover_name="deaths",
    animation_frame="year",
    title="Child Mortality Rates (2010-2020)",
)
map_fig.update_layout(showlegend=False)

```



# Home 

```{python}

# child_mort_pop_combined_subset = pd.DataFrame()
num_cols = child_mort_pop_combined_subset.shape[1]
num_rows = child_mort_pop_combined_subset.shape[0]
```


## {height="20%"}

::: {.valuebox title="Number of Columns" color="primary" icon="heart"}
`{python} num_cols`

some test here
:::

::: {.valuebox title="Number of Rows" color="secondary" icon="activity" }
`{python} num_rows`

test here
:::

::: {.valuebox title="Medium Number" color="success" icon="bar-chart"}
2
:::

## Row 1 {height="15%"}
The map below displays the 5 selected with a distribution of child mportality per country.

The bar chart on the right panel displays 10 selected countries with a distribution of mortality rates. 


## Row 2 {height="70%"}

### {width=70%}



```{python}

# Map goes here
map_fig
```


### {width=40%}


```{python}
bar_fig
```




# Table Section

Displaying the interactive table with itables of child mortality rates:

- Absolute change gives the exact units/values of difference between the selected years of 2010 and 2020.

- Relative change displays as a change in percentage from the starting figure.


```{python}

import itables
itables.show(table_df, buttons=["csvHtml5"]) 
```



# Chart Section

## Row 1 {height="70%"}

### Column {width="80%"}

```{python}

fig_chart.show()
```

### Column {width="30%"}

In the line chart, from the 5 selected countries, Sierra Leone and Nigeriaa shows to have high child mortality rates from 2010. 

Senegal seems to have the lowest death rates from 2010 to 2020 perhaps due to rapid child immunization campaigns.

The rates slowly declines, perhaps due to immunisation practices, such as polio, for children and aggressive immunization campagins against childhood diseases.


## Row 2 {height="70%"}

### Column {width="80%"}


```{python}


country_fig = px.bar(
    child_mort_pop_combined_subset,
    x="year",
    y="deaths",
    color="country",
    barmode="group",
  
    title="Distribution of Deaths by Country",
   
    hover_data=["country"],  # This adds country names to hover info
    color_discrete_sequence=px.colors.sequential.Turbo,  # Built-in Blues palette
).update_layout(
    showlegend=False, xaxis_title="Year", yaxis_title="Child Mortality"
)

country_fig
```



### Column {width="30%"}

In the bar chart, from the 5 selected countries, Sierra Leone and Nigeriaa shows to have high child mortality rates from 2010. 

Senegal seems to have the lowest death rates from 2010 to 2020 perhaps due to rapid child immunization campaigns.

The rates slowly declines, perhaps due to immunisation practices, such as polio, for children and aggressive immunization campagins against childhood diseases.



# About

**Goal**

In this final project, I will display relationships between child mortality, and under 5 population (0-5 years).

The goal is to clean and merge these raw datasets and produce tables and charts with the data.

The data was downloaded from Gapminder and the goal of this projec to produce a report with three pages:

- First Indicator Analysis
- Second Indicator Analysis
- Relationship between the two indicators. No statistical analysis is required; this can be purely descriptive/graphical.

**Data Import**

I have imported 2 *raw* datasets, 'child_mortality_0_5_years' and 'under 5 population' accessed from Gapminder Foundation.

1. **Child Mortality from 0 to 5 years**. (*data/child_mortality_0_5_year_olds_dying_per_1000_born.csv*).

According to Gapminder description, child mortality is the probability of dying between birth and exactly five years of age expressed in 1000 live births.

2. **Under Five Population**. (*data/u5pop.csv*).

According to Gapminder description, is the total number of children, aged 0-4 years old.

Loading the datasets into Python using 'pd.read_csv' to have an idea of the data structure.
